[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | migrations
  )/
)
'''

[tool.isort]
profile = "black"
src_paths=["source"]
line_length=120