# Generated by Django 4.2.6 on 2023-10-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("front_page", "0001_added_front_page_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="summary",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="solution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.solution",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.task",
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.comment",
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="solution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.solution",
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.task",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.comment",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="solution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.solution",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front_page.task",
            ),
        ),
    ]
